package entities

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/daoleno/uniswap-sdk-core/msgpencode"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *CurrencyAmount) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "Fraction")
			return
		}
		z.Fraction = nil
	} else {
		if z.Fraction == nil {
			z.Fraction = new(Fraction)
		}
		err = z.Fraction.DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, "Fraction")
			return
		}
	}
	{
		var zb0002 []byte
		zb0002, err = dc.ReadBytes(EncodeCurrency(z.Currency))
		if err != nil {
			err = msgp.WrapError(err, "Currency")
			return
		}
		z.Currency = DecodeCurrency(zb0002)
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "DecimalScale")
			return
		}
		z.DecimalScale = nil
	} else {
		{
			var zb0003 []byte
			zb0003, err = dc.ReadBytes(msgpencode.EncodeInt(z.DecimalScale))
			if err != nil {
				err = msgp.WrapError(err, "DecimalScale")
				return
			}
			z.DecimalScale = msgpencode.DecodeInt(zb0003)
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CurrencyAmount) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 3
	err = en.Append(0x93)
	if err != nil {
		return
	}
	if z.Fraction == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.Fraction.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Fraction")
			return
		}
	}
	err = en.WriteBytes(EncodeCurrency(z.Currency))
	if err != nil {
		err = msgp.WrapError(err, "Currency")
		return
	}
	if z.DecimalScale == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteBytes(msgpencode.EncodeInt(z.DecimalScale))
		if err != nil {
			err = msgp.WrapError(err, "DecimalScale")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CurrencyAmount) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 3
	o = append(o, 0x93)
	if z.Fraction == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.Fraction.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Fraction")
			return
		}
	}
	o = msgp.AppendBytes(o, EncodeCurrency(z.Currency))
	if z.DecimalScale == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendBytes(o, msgpencode.EncodeInt(z.DecimalScale))
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CurrencyAmount) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.Fraction = nil
	} else {
		if z.Fraction == nil {
			z.Fraction = new(Fraction)
		}
		bts, err = z.Fraction.UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, "Fraction")
			return
		}
	}
	{
		var zb0002 []byte
		zb0002, bts, err = msgp.ReadBytesBytes(bts, EncodeCurrency(z.Currency))
		if err != nil {
			err = msgp.WrapError(err, "Currency")
			return
		}
		z.Currency = DecodeCurrency(zb0002)
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.DecimalScale = nil
	} else {
		{
			var zb0003 []byte
			zb0003, bts, err = msgp.ReadBytesBytes(bts, msgpencode.EncodeInt(z.DecimalScale))
			if err != nil {
				err = msgp.WrapError(err, "DecimalScale")
				return
			}
			z.DecimalScale = msgpencode.DecodeInt(zb0003)
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CurrencyAmount) Msgsize() (s int) {
	s = 1
	if z.Fraction == nil {
		s += msgp.NilSize
	} else {
		s += z.Fraction.Msgsize()
	}
	s += msgp.BytesPrefixSize + len(EncodeCurrency(z.Currency))
	if z.DecimalScale == nil {
		s += msgp.NilSize
	} else {
		s += msgp.BytesPrefixSize + len(msgpencode.EncodeInt(z.DecimalScale))
	}
	return
}
