package entities

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/ethereum/go-ethereum/common"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *tokenInner) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "BaseCurrency")
			return
		}
		z.BaseCurrency = nil
	} else {
		if z.BaseCurrency == nil {
			z.BaseCurrency = new(BaseCurrency)
		}
		err = z.BaseCurrency.DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, "BaseCurrency")
			return
		}
	}
	{
		var zb0002 []byte
		zb0002, err = dc.ReadBytes((common.Address).Bytes(z.Address))
		if err != nil {
			err = msgp.WrapError(err, "Address")
			return
		}
		z.Address = common.BytesToAddress(zb0002)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *tokenInner) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	if z.BaseCurrency == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.BaseCurrency.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "BaseCurrency")
			return
		}
	}
	err = en.WriteBytes((common.Address).Bytes(z.Address))
	if err != nil {
		err = msgp.WrapError(err, "Address")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *tokenInner) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	if z.BaseCurrency == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.BaseCurrency.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "BaseCurrency")
			return
		}
	}
	o = msgp.AppendBytes(o, (common.Address).Bytes(z.Address))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *tokenInner) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.BaseCurrency = nil
	} else {
		if z.BaseCurrency == nil {
			z.BaseCurrency = new(BaseCurrency)
		}
		bts, err = z.BaseCurrency.UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, "BaseCurrency")
			return
		}
	}
	{
		var zb0002 []byte
		zb0002, bts, err = msgp.ReadBytesBytes(bts, (common.Address).Bytes(z.Address))
		if err != nil {
			err = msgp.WrapError(err, "Address")
			return
		}
		z.Address = common.BytesToAddress(zb0002)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *tokenInner) Msgsize() (s int) {
	s = 1
	if z.BaseCurrency == nil {
		s += msgp.NilSize
	} else {
		s += z.BaseCurrency.Msgsize()
	}
	s += msgp.BytesPrefixSize + len((common.Address).Bytes(z.Address))
	return
}
